export const etherscanApiUrls = {
  [1]: 'https://api.etherscan.io/api',
  [5]: 'https://api-goerli.etherscan.io/api',
  [11155111]: 'https://api-sepolia.etherscan.io/api',
  [10]: 'https://api-optimistic.etherscan.io/api',
  [420]: 'https://api-goerli-optimistic.etherscan.io/api',
  [137]: 'https://api.polygonscan.com/api',
  [80_001]: 'https://api-testnet.polygonscan.com/api',
  [42_161]: 'https://api.arbiscan.io/api',
  [421_613]: 'https://api-goerli.arbiscan.io/api',
  [56]: 'https://api.bscscan.com/api',
  [97]: 'https://api-testnet.bscscan.com/api',
  [128]: 'https://api.hecoinfo.com/api',
  [256]: 'https://api-testnet.hecoinfo.com/api',
  [250]: 'https://api.ftmscan.com/api',
  [4002]: 'https://api-testnet.ftmscan.com/api',
  [43114]: 'https://api.snowtrace.io/api',
  [43113]: 'https://api-testnet.snowtrace.io/api',
  [42220]: 'https://api.celoscan.io/api',
  [44787]: 'https://api-alfajores.celoscan.io/api',
  [8543]: 'https://api.basescan.org/api',
  [85431]: 'https://api-goerli.basescan.org/api',
  [7777777]: 'https://api.basescan.org/api',
} as const
